from queue import ArrayQueue


def main():
    print("-----TEST 0-----")
    queue0 = ArrayQueue()
    queue0.enqueue(1)
    queue0.enqueue(2)
    queue0.dequeue()
    print(queue0)
    print(queue0.dequeue())
    print(queue0)


    print("-----TEST 1-----")
    queue1 = ArrayQueue()
    queue1.enqueue(2)
    print(queue1)
    queue1.dequeue()
    print(queue1)
    queue1.enqueue(4)
    print(queue1)
    queue1.enqueue(8)
    print("First: " + str(queue1.first()))
    queue1.enqueue(5)
    print("First: " + str(queue1.first()))
    queue1.dequeue()
    queue1.enqueue(6)
    print(queue1)
    queue1.dequeue()
    queue1.dequeue()
    queue1.enqueue(7)
    print(queue1)

    print("\n-----TEST 2-----")
    queue2 = ArrayQueue()
    queue2.enqueue(2)
    queue2.enqueue(5)
    queue2.enqueue(14)
    queue2.enqueue(7)
    queue2.enqueue(3)
    queue2.enqueue(7)
    print(queue2)
    queue2.enqueue(89)
    queue2.enqueue(23)
    queue2.enqueue(7)
    print(queue2)
    queue2.dequeue()
    queue2.dequeue()
    print(queue2)
    queue2.enqueue(8)
    queue2.enqueue(9)
    print(queue2)
    print("First: " + str(queue2.first()))
    queue2.enqueue(15)
    queue2.enqueue(3)
    queue2.enqueue(7)
    queue2.enqueue(8)
    print("First: " + str(queue2.first()))
    queue2.enqueue(45)
    print(queue2)
    queue2.enqueue(34)
    queue2.enqueue(2)
    queue2.enqueue(5)
    print("First: " + str(queue2.first()))
    queue2.enqueue(9)
    print("First: " + str(queue2.first()))
    print(queue2)

    print("\n-----TEST 3-----")
    queue3 = ArrayQueue()
    queue3.enqueue(4)
    queue3.enqueue(19)
    queue3.enqueue(999)
    print(queue3)
    queue3.enqueue(1001)
    queue3.enqueue(29)
    queue3.enqueue(45)
    print(queue3)
    queue3.dequeue()
    queue3.dequeue()
    queue3.dequeue()
    queue3.dequeue()
    print(queue3)
    queue3.dequeue()
    queue3.dequeue()
    print(queue3)
    queue3.enqueue(10)
    print("First: " + str(queue3.first()))
    queue3.enqueue(5)
    queue3.enqueue(8)
    queue3.enqueue(10)
    queue3.enqueue(10)
    print("First: " + str(queue3.first()))
    queue3.enqueue(6)
    print(queue2)
    queue3.enqueue(77)
    print("First: " + str(queue3.first()))
    queue3.enqueue(57)
    print("First: " + str(queue3.first()))
    print(queue3)

    print("\n-----TEST 4-----")
    queue4 = ArrayQueue()
    queue4.enqueue(0)
    queue4.enqueue(9)
    queue4.enqueue(13)
    print(queue4)
    queue4.enqueue(1)
    queue4.enqueue(2)
    queue4.enqueue(0)
    queue4.enqueue(9)
    queue4.enqueue(5)
    print(queue4.get_size(), "Size of the list")
    print(queue4)
    queue4.dequeue()
    queue4.dequeue()
    queue4.dequeue()
    queue4.dequeue()
    print(queue4)
    queue4.dequeue()
    queue4.dequeue()
    queue4.dequeue()
    queue4.dequeue()
    print(queue4.is_empty(),"The queue is empty")
    print(queue4)
    queue4.enqueue(10)
    print("First: " + str(queue2.first()))
    queue4.enqueue(5)
    queue4.enqueue(8)
    queue4.enqueue(10)
    queue4.enqueue(10)
    print(queue4)

    print("\n-----TEST 5-----")
    queue5 = ArrayQueue()
    queue5.enqueue(0)
    queue5.enqueue(9)
    queue5.enqueue(13)
    print(queue5)
    queue5.enqueue(1)
    print(queue5.get_size(), "Size of the list")
    print(queue5)
    queue5.dequeue()
    queue5.dequeue()
    queue5.dequeue()
    queue5.dequeue()
    print(queue5)
    print("The queue is empty", queue5.is_empty())
    queue5.enqueue(420)
    print(queue5)

    print("\n-----TEST 6-----")
    queue6 = ArrayQueue()
    queue6.enqueue(0)
    queue6.enqueue(9)
    queue6.enqueue(13)
    queue6.enqueue(0)
    queue6.enqueue(9)
    queue6.enqueue(13)
    queue6.enqueue(0)
    queue6.enqueue(9)
    queue6.enqueue(13)
    print(queue6)
    queue6.enqueue(1)
    print(queue6.get_size(), "Size of the list")
    print(queue6)
    queue6.dequeue()
    queue6.dequeue()
    queue6.dequeue()
    queue6.dequeue()
    print(queue6)
    print("The queue is empty", queue6.is_empty())
    queue6.enqueue(420)
    print(queue6)

main()